### ISSUE TITLE
plugin request for money?

### ISSUE THREAD

**Issue by Alexey-T** [JairoMartinezA/cuda_terminal_j#2]
Hello @JairoMartinezA . I 've got request for a new plugin for money (150$ is first offer). work with www.seafile.com files - getting diff of current file with prev version, etc. Interested?

**Comment by JairoMartinezA** [comment]
Hi @Alexey-T,
Is the idea to create / use a kind of Project Manager connected to the seafile file server? I am reading about it, but I understand you can have the file server in your own infrastructure, right? I don't know if the server can be reached by URL or just like a local path. Have you more information?

**Comment by Alexey-T** [comment]
I have the request for plugin, pls email me to support(at)uvviewsoft.com so I can send it
